// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pupwovjdofdzzqktywae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1cHdvdmpkb2Zkenpxa3R5d2FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNTg0MjAsImV4cCI6MjA2MzYzNDQyMH0.cBU0CscEUwL0kPiAcAw6MRhgfR4NfC_w4yyd_1NbIFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});